ANXS/postgresql

defaults/main.yml
tasks/configure.yml
tasks/databases.yml

Sometimes you want to run postgres with a non default user (`postgres`), for example `nobody` like is my case because I start postgres with supervisord.
I added 2 more vars:
postgresql_service_user
postgresql_service_group
By default they work like always, they use `postgresql_service_user` and this by default `postgres`, so the default behaviour is `postgres` user

Added user service option in case you run postgres with a not default user

---

tasks/databases.yml
tasks/install.yml

I tried to use this role to setup postgresql, and it worked great except for the `uuid-ossp` part (it needs the `postgresql-contrib` package installed). Also, running `ansible-playbook` on hosts that have already had the postgresql role applied successfully will result in Ansible reporting the `uuid-ossp` installation as having changed (even though the output says `NOTICE:  extension "uuid-ossp" already exists, skipping`).
This PR includes:
- BUGFIX: installs `postgresql-contrib` package for uuid-ossp extension support
- BUGFIX: added checks on "Add uuid-ossp..." task within `databases.yml` so Ansible won't incorrectly report the uuid extension installation as "changed" on each run.

add installation of postgresql-contrib for uuid-ossp, and fix reporting of uuid-ossp as "changed" on each run.

---

tasks/databases.yml
tasks/users.yml

When re-defining `postgresql_port` from the default value of `5432` the database tasks fail due to a connection failure. Adding the `postgresql_port` to the ansible module `postgresql_db` resolves the issue.

Corrected database tasks when custom ports are defined

---

tasks/users.yml

This should fix #55 by allowing `postgresql_user_privileges: [{name: foo, db: "bar", priv: "ALL", role_attr_flags: "CREATEDB"}],`

Add role_attr_flags to postgresql_user

---

tasks/databases.yml

Installs more postgres extensions (namely: cube, plpgsql and earthdistance)
I also remove `sudo` and `sudo_user` in favour of `--username` from the directives, as you don't necessarily have a system user with the same name as the postgres admin one. :)
Thanks for the hard work, made my life that much easier!

Install extra postgres extensions

---

tasks/users.yml
tasks/users_privileges.yml
test.yml
vars/test.yml

Somehow user privileges where being changed on `tasks/users.yml`, before the databases where created causing errors. I moved all user privileges to `tasks/users_privileges.yml` merging the options that where there.
This bug is affecting _master_ after yesterday's merges.

Merges user privilages into correct role

---

defaults/main.yml
tasks/install.yml

These settings are very useful to allow the use of a custom repository (built with apt-mirror or other tools) on hosts with no access to Internet.
It also fixes #60 if we want to use this role on standard distribution repositories (even if it is not supported officially, which is understandable).

Add some APT settings into variables allowing to set a custom (mirror) repository

---

tasks/extensions/contrib.yml
tasks/extensions/dev_headers.yml
tasks/extensions/postgis.yml
tasks/install.yml

Hey!
Love the playbook, it's awesome! Ran into an issue with a fresh Trusty cloud image today, a stale APT cache leading to a 404 on the Postgres package site. I've added apt-get update behaviour with a validity timer of one day right after adding the apt repo (no point in updating the cache before adding the repo).
This works well for me on a fresh installation, let me know what you think!
Timo

Added apt cache update/valid-time, re-ordered apt repo/key installation

---

tasks/install.yml

This lets us set the variables to False to use the packages provided by the distribution without further ado.

Only do APT tasks if variables have true values

---

.travis.yml
README.md
meta/main.yml
tasks/configure.yml
tasks/install.yml

Check registered locales and register, generate locale if need be
To test this, change the default locale to something obscure like `en_SG.utf8` then run vagrant up (without this fix) you should see smth like:
```
failed: [anxs.local] => (item={'name': 'foobar'}) => {"failed": true, "item": {"name": "foobar"}}
msg: Database query failed: invalid locale name: "en_SG.utf8"
```
Now try with this fix on a fresh box, and it should work

Generate locale if it hasnt yet been done

---

.travis.yml
README.md
tasks/users_privileges.yml

Used 'default(omit)' where appropriate.
Bumped Ansible requirement to v1.8+ (needed for 'default(omit)' functionality).
This is also enables this use case:
```yaml
postgresql_user_privileges:
- name: "{{ genesis_postgresql_user }}"
role_attr_flags: "CREATEDB,NOSUPERUSER"
```
With current version of `postgres` role, the above use case fails with:
```
Perform task: postgresql | PostgreSQL | Update the user privileges (y/n/c):  *** 
fatal: [some-host] => One or more undefined variables: 'dict object' has no attribute 'db'
```

Improved users' privileges handling.

---

defaults/main.yml
tasks/install.yml
templates/etc_apt_preferences.d_apt_postgresql_org_pub_repos_apt.pref.j2

This is very useful on systems where `apt` is configured with multiple repositories with different `Pin-Priority` settings.
A user can set the `Pin-Priority` of PGDG's Apt repository to a higher number than, for example, the `Pin-Priority` of stable Debian release repository to prefer installing the PostgreSQL packages from PGDG's repository rather than stable.
In some cases, this solves the problem of not being able to install PostgreSQL from PGDG's repository at all due to unresolvable dependencies.

Added ability to set Pin-Priority of PGDG's Apt repository.

---

tasks/install.yml

Fixes #85
When `ca-certificates` is uninstalled, the role failed with the default configuration with the following message:
`msg: Failed to validate the SSL certificate for www.postgresql.org:443. Use validate_certs=no or make sure your managed systems have a valid CA certificate installed. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible`.

Install ca-certificates before doing apt_key

---

tasks/databases.yml

One of my playbooks was failing the idempotence check, so I updated the hstore ext task with `changed_when` and `failed_when`, like `uuid-ossp`.
Current output (when task is repeated):
```
TASK: [ANXS.postgresql | PostgreSQL | Add hstore to the databases with the requirement] *** 
<127.0.0.1> REMOTE_MODULE command psql rails_1 --username postgres -c 'CREATE EXTENSION IF NOT EXISTS hstore;' #USE_SHELL
changed: [default_server] => (item={'citext': True, 'name': 'rails_1', 'uuid_ossp': True, 'hstore': True}) => {"changed": true, "cmd": "psql rails_1 --username postgres -c 'CREATE EXTENSION IF NOT EXISTS hstore;'", "delta": "0:00:00.100098", "end": "2015-11-02 06:54:07.552808", "item": {"citext": true, "hstore": true, "name": "rails_1", "uuid_ossp": true}, "rc": 0, "start": "2015-11-02 …
```

Add failed_when and changed_when to hstore ext task

---

tasks/install.yml

This fixes the following issue with recent (2.0.0) version of ansible:
fatal: [my_host]: FAILED! => {"failed": true, "msg": "ERROR!  environment must be a dictionary, received postgresql_env (<class 'ansible.parsing.yaml.objects.AnsibleUnicode'>)"}

Explicitely extrapolate the environment parameter

---

defaults/main.yml

Setting all of the `postgresql_lc_*` vars to that of `postgresql_locale` so you need only change locale in one variable..

Making changing of locale easier

---

defaults/main.yml
templates/postgresql.conf-9.3.j2
templates/postgresql.conf-9.4.j2

to set the value automatically following the database (PostgreSQL default configuration).
Currently the ``postgresql_client_encoding`` is set with the ``sql_ascii`` value, causing problems which should not happen on a default installation (e.g https://github.com/osiell/ansible-odoo/issues/23).
This PR leaves the ``client_encoding`` option commented (as it is done in the upstream configuration file: https://github.com/ANXS/postgresql/blob/master/templates/postgresql.conf-9.4.orig#L534), unless the user set a value in the ``postgresql_client_encoding`` role option.

[FIX] 9.3 + 9.4 - Do not active the 'client_encoding' option by default

---

defaults/main.yml
handlers/main.yml
tasks/configure.yml
tasks/databases.yml
tasks/extensions/contrib.yml
tasks/install_yum.yml
tasks/main.yml
tasks/users.yml
templates/etc_systemd_system_postgresql.service.d_custom.conf.j2
vars/Debian.yml
vars/RedHat.yml
vars/empty.yml

This seems to be a very nice role. I needed support for CentOS and RedHat from Postgres' YUM repository, so I figured I'd share. So far, this is only tested on CentOS 7.1. There's plenty more that can be done to clean up the multi-distro support further, but hopefully this is useful enough as it is. I noticed the recent request in #106, so hopefully this can start to address this as well.
Thanks!

Add CentOS/RedHat support, with the exclusion of dev_headers and postgis

---

README.md

This PR adds installation instructions via `ansible-galaxy` to the README.

readme: add installation instructions with `ansible-galaxy`

---

tasks/databases.yml

When a playbook is ran, a few of the tasks are prefixed with `postgresql` vs. `PostgreSQL`, this PR addresses usage of `postgresql`.

tasks: use PostgreSQL across all tasks

---

tasks/main.yml

The `vars` file is not loaded if we run a playbook with the `postgresql` tag, which produces an error:
```
TASK: [ANXS.postgresql | PostgreSQL | Ensure PostgreSQL is running] *********** 
fatal: [HOST] => One or more undefined variables: 'postgresql_service_name' is undefined
FATAL: all hosts have already failed -- aborting
```

[FIX] Tag added on include_vars task

---

.travis.yml
defaults/main.yml
templates/HOWTO.postgresql.conf
templates/postgresql.conf-9.1.j2
templates/postgresql.conf-9.1.orig
templates/postgresql.conf-9.2.j2
templates/postgresql.conf-9.2.orig

This PR:
- add support for PostgreSQL 9.1 (`postgresql.conf.9.1.orig` + `postgresql.conf.9.1.j2`)
- add support for PostgreSQL 9.2 (`postgresql.conf.9.2.orig` + `postgresql.conf.9.2.j2`)
- update the `defaults/main.yml` file (add related version options, and add some `(>= 9.X)` or `(<= 9.X)` comments)
- update the Travis CI configuration:
* remove all the pre-installed PostgreSQL servers in the Travis environment
* reduce the `shared_buffers` value to 32Mb instead of 128Mb (default), otherwise PostgreSQL 9.1 and 9.2 don't start on Travis
- add a HOWTO explaining the general method I use to add a new PostgreSQL version
Fix #21

Add support for PostgreSQL 9.1 and 9.2.

---

vars/RedHat.yml

Some versions of psql look for the socket in /tmp, others in the pid

---

README.md
defaults/main.yml
tasks/databases.yml

I saw another PR for this but it was old and had backwards incompatible changes so I made a new one that is backwards compatible.
While working on it I thought it would be much nicer if the extensions key could be listed under each database like:
```
postgresql_databases:
- name: foobar
extensions:
- hstore
- citext
```
but that would make it backwards incompatible because the `with_subelements` loop can't handle missing keys.  There is support for that in [ansible v2](https://github.com/ansible/ansible/pull/10995) though so maybe in the future we could change it to use that.
So the new syntax for extensions is:
```
postgresql_database_extensions:
- db: foobar
extensions:
- hstore
- citext
```

Add variable extension support

---

.travis.yml

Somehow this made it into master with https://github.com/ANXS/postgresql/pull/124 
This fixes the build by ensuring no prompts are given on `apt-get autoremove`..

Remove prompts on travis postgres cleanup

---

.travis.yml
README.md
meta/main.yml

Bumping as it fixes the use of the `update_cache` argument when running against centos hosts..

Bump minimum ansible version to latest on pypi (1.9.4)

---

.travis.yml
tasks/configure.yml
tasks/databases.yml
tasks/install_yum.yml
tasks/users.yml
tasks/users_privileges.yml
tests/playbook.yml

Add Ansible 2.0.0.2 to Travis-CI. Use become/become_user instead of sudo/sudo_user.
Environment must be expressed as a template variable in Ansible >= 2.0 to avoid this error with yum:
```
TASK [jesselang.postgresql : PostgreSQL | Make sure the dependencies are installed] ***
ok: [hz-single] => (item=[u'python-psycopg2', u'python-pycurl', u'glibc-common'])
TASK [jesselang.postgresql : PostgreSQL | Install PostgreSQL] ******************
[DEPRECATION WARNING]: Using bare variables for environment is deprecated.
Update your playbooks so that the environment value uses the full variable
syntax ('{{foo}}'). This feature will be removed in a future release.
Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.
fatal: [hz-single]: FAILED! => {"failed": true, …
```

Ansible 2 compatibility

---

.travis.yml
Vagrantfile
tests/Dockerfile-centos6
tests/Dockerfile-ubuntu14.04

Aims to get the role running against a centos host, and makes a first rough stab at https://github.com/ANXS/postgresql/issues/115...
I'm trying to find the time to work through the issues and pull requests in this repo, though now we have centos support, I'm increasing aware that every bit of new code will need to be tested on centos.. so getting this code up prematurely to ensure we are at least building (albeit a little slow, and not testing idempotence.. yet)
Fixes #115

Travis testing centos/ubuntu with docker

---

tasks/users.yml
tests/vars.yml

their permissions without requiring that the user's password be
specified. Also, this seems more secure than a default of 'pass'.

Omit user passwords to allow creation and verification of a user and

---

tests/Dockerfile-centos6
tests/Dockerfile-ubuntu14.04

This fixes the Travis builds. There must have been some dependency changes involving the Python cryptography module.

Add cryptography dependencies

---

templates/HOWTO.postgresql.conf
templates/etc_monit_conf.d_postgresql.j2
templates/pg_hba.conf.j2
templates/postgresql.conf-9.1.j2
templates/postgresql.conf-9.2.j2
templates/postgresql.conf-9.3.j2
templates/postgresql.conf-9.4.j2
templates/postgresql.conf-9.5.j2

When looking at configuration files on a host, it's often helpful to
know when the file was generated by a configuration management tool.
Ansible provides this through the `ansible_managed` context variable.

Add ansible_managed to templates

---

tasks/install_yum.yml

Required for hstore and other extensions.
Debian-based distros already got them in commit 8861657.

Install postgresql-contrib module on EL-distros

---

defaults/main.yml

```
TASK: [postgresql | PostgreSQL | Add PostgreSQL repository]
*******************
failed: [anxs.local] => {"changed": false, "failed": true, "rc": 1}
msg: Package at
http://yum.postgresql.org/9.5/redhat/rhel-6-x86_64/pgdg-scientific95-9.5-2.noarch.rpm
could not be installed
FATAL: all hosts have already failed -- aborting
```

Fixed Scientific Linux installation

---

.travis.yml
defaults/main.yml
templates/postgresql.conf-9.6.j2
templates/postgresql.conf-9.6.orig
tests/vars.yml

Replaces #204 
- Add configuration template for PostgreSQL 9.6
- Update variables and comments in defaults/main.yml
- Update test.yml to use 9.6
- Add role options for 9.6 to .travis.yml
- Update the 2.x version of Ansible in .travis.yml to 2.1.2.0
- Use specific release numbers for each distribution / version

Add compatibility for PostgreSQL 9.6

---

tasks/install.yml

If you want to execute the role on a system with enabled apt pinning, you will get an error due to the missing dependency's. With this patch, apt resolves correctly and allows installation of postgresql.

fixed install problems on debian with pinning enabled

---

tasks/install.yml

This is to allow certain versions to be installed which require a custom source.
My specific use case:
Installation on an arm64 board, which is not supported by the official PostgreSQL sources, but available through jessie-backports.
This would allow me to simply do:
```yaml
vars:
postgresql_default_release: jessie-backports
roles:
- role: ANXS.postgresql
```
(I noticed that just the [last commit/PR](https://github.com/ANXS/postgresql/pull/229) added the `default_release` parameter, this extends it further)

Allow a custom default_release

---

tasks/configure.yml
tests/Dockerfile-centos6
tests/Dockerfile-ubuntu14.04

rhel6 doesn't allow to have configuration files in a separate directory than the data directory. The sysV init script that ships with postgresql doesn't allow to change the configuration directory.
if `postgresql_data_directory` is `/var/lib/pgsql/9.3/data/` then `postgresql_conf_directory` has to be the same. 
If you set `postgresql_conf_directory` to `postgresql_data_directory` postgresql won't start because of too wide permission on the data directory. This PR reduce the file permission on the conf directory from `750` to `700` and fix the issue altogether.

change permission on the conf directory

---

.travis.yml
README.md
meta/main.yml
tasks/extensions.yml
tasks/main.yml

Converted to use `import_tasks` instead of `include`, to remove the Depracation warning.  Fixes #290

Updated to use "import_tasks" instead of "include"

---

tasks/databases.yml
tests/docker/group_vars/postgresql.yml

Replace https://github.com/ANXS/postgresql/pull/295
ping @gclough

Use postgresql ext for extensions

---

meta/main.yml

Fixes #141
This should update the Galaxy metadata to show that this role supports:
Ubuntu
Debian
CentOS
RedHat
... I've also added some extra tags at the bottom, to help people searching for it

Added meta data for CentOS and RedHat, plus added tags

---

meta/main.yml

Fixed naming for CentOS/RedHat, and added even more tags.  Update for #312

Fixed CenOS/RedHat naming... should be EL

---

defaults/main.yml

There was some issue with string variables (i.e. #254) that can also have options such as "on/off"... so to make it explicit, all string variables should be quoted.
I've also tidied up the usage of `{{var}}`, and converted them all to be `{{ var }}` (with spaces)
Finally, I tried to make quoting consistent, by moving all (most?) of the strings from using single quotes `' '` to double quotes `" "`.

Quote all string variables, and add spaces around variables "{{ var }}"

---

handlers/main.yml
tasks/configure.yml
tasks/install_yum.yml

the remaining question is which task should call the handlers.

added the use of handlers

---

README.md

To let people know that the project is active, we should show that we're looking to the future... first with v10 compatibility, but then with v11 which is out in 6 months from now.
I also fixed the spelling of "CentOS", to match the convention:
https://wiki.centos.org/FAQ/General#head-4b2dd1ea6dcc1243d6e3886dc3e5d1ebb252c194

Prepare for PostgreSQL v10 (and v11)

---

tasks/configure.yml

Fixes #328 ... but this will been reviewing in context of #294, as all restart/reload is done by handlers in a different way.  We can probably just replace this with:
`include_tasks: "{{ role_path }}/handlers/reload.yml"`

Reload conf parameters after install, so that pg_hba.conf is re-read

---

tasks/install_yum.yml

For selinux enabled linux systems libselinux-python must be installed for ansible to work properly,
see [ansible-doc](http://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html). Missing on some installations.

Added libselinux-python dependency for selinux enabled redhat systems.

---

README.md
tasks/install_yum.yml

We should have a special place for the creator, and those that oversee the project now.

Honour those that created the role in the first place

---

.travis.yml

The missing PostgreSQL v9.3 version for Fedora is causing the build to fail, so I've disabled it until we can make it skip this specific platform/version combination.
There will never be a pre-packaged v9.3 for Fedora, so we need to handle this situation gracefully.

Disable Fedora testing, as PostgreSQL v9.3 doesn't exist

---

defaults/main.yml
tasks/configure.yml
tests/docker/group_vars/postgresql.yml

Fixes #283 , and supersedes #246 .
This change allows you to include:
--data-checksums
--xlogdir / --waldir (depending on version of PostgreSQL)
--pwfile
I believe these are all of the possible command line options usable with initdb, so it should be complete coverage.  For Debian it passes them to `pg_createcluster`, and RedHat it uses `initdb`.
*NOTE:* Checksums are controlled by the `postgresql_data_checksums` variable, which I've set to false.  I believe this should almost always be turned on, but I'm sticking with the PostgreSQL convention of it being optional.  If we wanted to help out new users then we could default this to true, but unless the PostgreSQL project does that first, then I'd be hesitant to add in any unexpected behaviour changes.

Allow use of "--data-checksums", "--xlogdir / --waldir", and "--pwfile" during initdb

---

handlers/main.yml
tasks/configure.yml
tasks/extensions/dev_headers.yml

This mostly refers to <https://github.com/ANXS/postgresql/issues/361>, but perhaps also helps <https://github.com/ANXS/postgresql/issues/329>.
Currently installation of extensions is broken with an error of a undefined handler. This happens because they still refer to the generic handler instead of the service or systemd specific ones.
Like @evaryont mentioned in issue #361 the use of two separate handlers to restart the Postgresql service is not required. 
Ansible's service module is designed to be an abstraction, so you do not have to worry about what "init system" is in control of the services. It has no relation to the `service` command that's going away on RedHat based system. Ansible's service module figures out when a host uses SysV init, systemd, OpenRC, upstart, rcctl, <other …

Resolve #361 : Use Ansible service module for restarting Postgresql

---

tasks/configure.yml

On Ubuntu (xenial), passing the --start flag to pg_createcluster  and --stop flag to pg_dropcluster confuses systemd and breaks the script's ability to restart postgres after resetting the cluster (leading to a situation where ansible thinks everything is fine but postgres is left wrongly running an old cluster until forcibly restarted).
Solution is to explicitly stop the postgres service before dropping the cluster, issue 'systemctl daemon-reload' after creating the new cluster and then start postgres again (note: strictly speaking we shouldn't need to start postgres again as this will be done by the restart task at the end of the file - I've kept it in since that's how the original script was written).

Fixed resetting cluster on Ubuntu (xenial)

---

defaults/main.yml

Using the string `'off'` actually causes `force_parallel_mode` to be `'on'` because the conf checks for the boolean value of `force_parallel_mode`.

Use boolean off for parallel mode

---

defaults/main.yml
templates/postgresql.conf-10.j2
templates/postgresql.conf-9.1.j2
templates/postgresql.conf-9.2.j2
templates/postgresql.conf-9.3.j2
templates/postgresql.conf-9.4.j2
templates/postgresql.conf-9.5.j2
templates/postgresql.conf-9.6.j2

Fixed force_parallel_mode. My commit is more generic, than https://github.com/ANXS/postgresql/pull/369
Fixed hot_standby_feedback defaults.

Fixed force_parallel_mode and hot_standby_feedback config defaults

---

templates/postgresql.conf-10.j2
templates/postgresql.conf-11.j2
templates/postgresql.conf-9.5.j2
templates/postgresql.conf-9.6.j2

Add cluster_name, and remove duplicate update_process_title config parameters

Add cluster_name, and remove duplicate update_process_title config parameters

---

.travis.yml
Vagrantfile

Add Fedora back to Vagrant tests. #393 fixed this.

Add Fedora back to Vagrant tests. #393 fixed this.

---

defaults/main.yml
templates/pg_hba.conf.j2

**Warning: this change will break installations which depend on the insecure default used before.**
The former default pg_hba config let any local POSIX user, and any local process, connect to postgres as any role including SUPERUSER, without providing a password.
This changes the default values to safer ones:
- local connections (via unix sockets) are now restricted to the role with the same name as the POSIX user
- localhost network connections are subject to MD5 password authentication
Those values are already used by default in distributions such as Debian and Ubuntu when pg_hba.conf is configured by apt instead of this role.
Also add a new variable to easily insert MD5-authenticated hosts - my understanding is that this is now the standard password scheme.
`root` is still allowed to …

More secure default authentication schemes

---

defaults/main.yml
tasks/fdw.yml
tasks/main.yml
vars/Debian.yml
vars/RedHat.yml
vars/xenial.yml

This adds the option to install [PostgreSQL Foreign Data Wrappers](https://wiki.postgresql.org/wiki/Foreign_data_wrappers) to access remote objects.
I've added support for the MySQL and OGR wrappers. This adds two configurable boolean options, which I added to the defaults:
```
postgresql_fdw_mysql: no
postgresql_fdw_ogr: no
```
Hope this helps someone.

Allow installation of PostgreSQL Foreign Data Wrappers (MySQL and OGR)

---

templates/postgresql.conf-9.5.j2

Removed duplicate cluster_name in 9.5

Removed duplicate cluster_name in 9.5

---

tasks/check_pg_version_mismatch.yml
tasks/main.yml

Check Binary/Database versions match, otherwise restart.  This can happen when something has upgraded the PostgreSQL binaries, but the cluster hasn't been restarted.  (Like what happened to me when the Ansible play failed half way through after a network error).
This tests allows the role to be more idempotent, and if you upgrade but fail to restart... then the next time it will detect that fact and call the restart handler.

Check Binary/Database versions match, otherwise restart

---

README.md

The original setting for this is broken for versions of PostgreSQL that are >=10, it no longer accepts unencrypted passwords.
note calling out change
set the default for `encrypted` to `yes`
md5 encrypted password of `pass`

Update readme example with encrypted password and encrypted: yes

---

meta/main.yml

Updated Galaxy metadata to include Fedora

Updated Galaxy metadata to include Fedora

---

defaults/main.yml

Removed unused default variables (as in not used ANYWHERE).  Checked with:
```
#!/bin/bash -
cat defaults/main.yml | grep ^[a-z] | cut -f1 -d: | while read VAR; do
echo $VAR
COUNT=`grep -r $VAR * | wc -l`
echo $COUNT
if [ $COUNT -le 1 ]; then
echo ERROR;
fi;
echo =====================================================
done | less
```
I've also moved some of them to a more logical location.

Removed unused variables, as they add to confusion

---

tasks/configure.yml

This will allow the use of C.UTF-8 on Debian and Ubuntu, as discussed in #430
https://github.com/ANXS/postgresql/issues/430
The background is that the ansible module locale_gen fails when checking for the availability of C.UTF-8, which can be assumed to exist on all systems.

Fix using C.UTF-8 in Debian/Ubuntu

---

README.md

Hi,
Readme says:
postgresql_default_auth_method: "trust"
but default/main.yml:
postgresql_default_auth_method: "peer"
Our proposal is to update de README.md but the default value changed on main.yml on commit:
b4f97394e1f0e5505c5038746513794549a06d91
If you haven't set this variable an used this role as is (as we did on our development environment) is a little bit tricky.
Anyway thanks in advance for sharing this role.

Updated README.md to show postgresql_default_auth_method 

---

vars/bionic.yml

Since, just like Ubuntu 16.04, Ubuntu 18.04 has some divergent variables
that need to be set. The PostGIS plugin, for instance, isn't installable
without these variable values.
This PR adds a vars file for Ubuntu 18.04 with variables that are
specific to that family.

Add a vars File for Ubuntu 18.04 Bionic

---

templates/postgresql.conf-9.3.j2

These changes are propagated from the 9.4 config template. 
Without these changes, PostgreSQL service doesn't start for me, rightfully claiming that the config is invalid. 
Unfortunately, I couldn't test them with Vagrant, but I ran this against my local installation and it was fine. 
Thank you in advance!

template/postgresql.conf-9.3.j2: Don't use the include variables if they are False. 

---

tasks/check_pg_version_mismatch.yml
tasks/databases.yml
tests/vars.yml

I added `PGPORT` environment variable for each task using `psql` client where it need to connect to the database.
I also change the `postgresql_port` in tests to check that everything work fine.

Fix #445: PSQL tasks fails when postgresql_port != 5432 (default value)

---

templates/postgresql.conf-11.j2
templates/postgresql.conf-12.j2

In this file (I haven't checked all the others, except pg-10), the choose_sync var wasn't being specified.
This copies the logic to render the string from the pg-10 template.
Docs: https://www.postgresql.org/docs/12/runtime-config-replication.html#GUC-SYNCHRONOUS-STANDBY-NAMES

Update sync standby names to include choose keyword

---

README.md
tasks/databases.yml
tasks/users.yml
tests/docker/group_vars/postgresql.yml
tests/vars.yml

this allows configuring the state for databases and users. Default is present as it was previously.

allow setting state for postgresql_databases and postgresql_users

---

templates/postgresql.conf-10.j2

With PostgreSQL 10, `password_encryption` is no longer a boolean.
It expects either `md5` or `scram-sha-256`.
The value `on` is kept as an alias of `md5` for backward compatibility.

Update password_encryption for PostgreSQL 10

---

README.md

Replace travis-ci.org with travis-ci.com

---

README.md

* fixed existing example how to include this role (fixed case)
* become global scope changed to role-only
* added new example how to include this role as task

README.md example fixed and added include-as-task example

---

README.md

Was setting up the ansible role and it appears case matters? Figured I'd update the readme.

Lowercase for Ansible Galaxy Install

---

.travis.yml
README.md
defaults/main.yml
meta/main.yml
templates/postgresql.conf-13.j2
templates/postgresql.conf-13.orig
tests/docker/group_vars/all.yml
tests/docker/images/Dockerfile.centos.8-builded
tests/docker/images/Dockerfile.debian.10-builded
tests/docker/images/Dockerfile.ubuntu.18.04-builded
tests/docker/images/Dockerfile.ubuntu.20.04-builded
tests/vars.yml
vars/postgresql_12.yml
vars/postgresql_13.yml
vars/postgresql_9.5.yml
vars/postgresql_9.6.yml

Added support for PostgreSQL v13

feat: Support PostgreSQL v13

---

defaults/main.yml
tasks/configure.yml

When creating tablespaces on PostgreSQL using "CREATE TABLESPACE"
statements, PostgreSQL requires that these directories already exist[1].
Allow creating tablespace directories from this role.
1. https://www.postgresql.org/docs/10/sql-createtablespace.html
Co-authored-by: Samuel Githengi <samuel.githengi@gmail.com>
Signed-off-by: Jason Rogena <jason@rogena.me>

Allow Creating Directories for Tablespaces

---

tasks/databases.yml

Hello!
Right now you can't run playbook that add a new database with extension in [check mode](https://docs.ansible.com/ansible/latest/user_guide/playbooks_checkmode.html) (`ansible-playbook --check [...]`) because `postgresql_ext` module trying to connect to database that was not created on previous step (because of check mode, yep).
So I suggest to skip errors if `ansible_check_mode` is set to `true`. Or may be is there another good way to fix it?
---
Test playbook that I used:
```
---
- name: Deploy
gather_facts: yes
become: true
hosts:
- seleznev-test-pg
vars:
postgresql_databases:
- name: test1
postgresql_database_extensions:
- db: test1
extensions:
- uuid-ossp
roles:
- ANXS.postgresql
```
Running playbook with `--check` (database `test1` doesn't exist at this moment):
```
TASK …
```

Ignore errors in "Add extensions to the databases" task in check mode

---

defaults/main.yml
tasks/configure.yml
tasks/schemas.yml
tasks/users.yml

Hi,
This small pull request allows user to hide current plain-text passwords into execution output with the new variable `postgresql_hide_passwords`.
The default value of this variable is `false` to allow users to activate this feature if they need it without changing their current usage.
Thank you.

postgresql_hide_passwords

---

Vagrantfile
vagrant-inventory

Working vagrant conf files with jammy64 image

jammy64 only

---

README.md
defaults/main.yml
tasks/extensions.yml
tasks/extensions/extra_packages.yml
tasks/install_rhel.yml
tasks/main.yml
templates/postgresql.conf-14.j2
templates/postgresql.conf-15.j2
vars/RedHat_9.yml
vars/extra_packages.yml

- add support for RHEL 9+
- add Rockylinux line in compatibility matrix
- feature to optionally add other repos and packages
- bug fix for extension_destdir required for debian distros only

RHEL 9+, additional repos and packages feature

---

.github/workflows/ci.yml
.github/workflows/stale.yml
README.md
molecule/README.md

- Update ci workflox (fix duplicate)
- Update readme with recent dropping tests on PG10

Update workflow & Update Readme

---

README.md
defaults/main.yml
molecule/README.md
molecule/default/molecule.yml

Remove pg 11 testing because pg11 is no longer available on postgresql repositories
Update compatibility matrix on readme (drop testing + prepare pg16)

566 remove postgresql 11 testing

---

README.md
defaults/main.yml
tasks/configure.yml
templates/pg_hba.conf.j2
templates/pg_ident.conf.j2
templates/postgresql.conf-10.orig
templates/postgresql.conf-11.orig
templates/postgresql.conf-12.orig
templates/postgresql.conf-13.orig
templates/postgresql.conf-15.orig
templates/postgresql.conf-16.j2
templates/postgresql.conf-16.orig
vars/Debian_22.yml
vars/postgresql_16.yml

- Add the necessary configuration templates to support PostgreSQL 16 installations.
- Update documentation (readme, role defaults, templates, ...)
resolves #565

support PostgreSQL 16

---

.github/workflows/ci.yml
.github/workflows/stale.yml
README.md
molecule/default/molecule.yml
tests/vars.CentOS.9.yml

- Add pg 16 testing
- Support testing for rockylinux9, debian12 and ubuntu20.04

Add pg16 testing
