ANXS/postgresql

.travis.yml, README.md, Vagrantfile, vagrant-inventory
- Add VagrantFile
- Add idempotence test
- Add inventory for vagrant
Following suit from https://github.com/ANXS/nodejs/pull/18 cheers @otakup0pe
=> Add vagrantfile and idempotence test

README.md, Vagrantfile, vagrant-inventory
Updating vagrant IP to avoid conflict with other repos in the organisation
=> Update vagrant ip

defaults/main.yml, tasks/configure.yml, tasks/install.yml
I propose to add options to let pgtune set the parameters in postgresql.conf .
This lets us get good performance out of postgres with the bare minimal of involvement (all pgtune parameters are optional).
=> Propose to create the config file with pgtune

README.md, tasks/databases.yml
=> add citext extension support

tasks/extensions/contrib.yml
=> Use yum to install contrib on CentOS, not apt.

.travis.yml, README.md, Vagrantfile, tests/playbook.yml, tests/vars.yml, vagrant-inventory
Getting increased activity in this project, so I wanted to make some changes that would allow for easier testing of things.. namely pulling the test vars into the test playbook, but also a little tidy up
- Rename test playbooks and move vars into tests dir
- Ensure Vagrantfile uses vagrant key, so we can provision using ansible directly
- Include test vars into test play
- update README to reflect changes
=> Improved testing and dev tools

README.md, defaults/main.yml, tasks/configure.yml, tasks/databases.yml
Added possibility to override locales per database.
=> Locales per database

README.md, defaults/main.yml, tasks/configure.yml, tasks/install_yum.yml
Please add option to enable service on the system
=> Option to enable service

defaults/main.yml
postgresql_synchronous_commit with raw on outputs to "True" in configuration file. Set it as a string fix this issue
=> postgresql_synchronous_commit should be a string

tasks/extensions/dev_headers.yml
- Added Added CentOS / RedHat support for installing development headers
=> dev_headers — Added CentOS / RedHat support

tasks/install.yml
=> Use a boolean value for compatibility with the latest Ansible

Vagrantfile, defaults/main.yml, tasks/extensions/postgis.yml, vars/xenial.yml
Fixed issue for install PostGIS extension with Ubuntu/Xenial distribution.
=> Fix for issue #183

tasks/users.yml
Ref: http://docs.ansible.com/ansible/latest/faq.html#how-do-i-keep-secret-data-in-my-playbook
=> Hide password from logs (fixes #215)

Vagrantfile
this lets you use different providers like libvirtd,vmware and vbox.
=> change vagrantfile to point to the official centos images since those support different providers.

tasks/extensions/postgis.yml, tests/docker/group_vars/postgresql.yml
Fixes #304 
Added extra checks for:
```
postgresql_databases="travis_test_database"
postgresql_database_extensions="adminpack,pgcrypto"
postgresql_users="travis_test_user1, travis_test_user2"
postgresql_ext_install_contrib=true
postgresql_ext_install_postgis=true
postgresql_pgtune=true
```
=> Increase the travis test coverage to include popular options

.gitignore, tasks/install_yum.yml
this should help reduce the yum calls and do them together.
=> changed install_yum.yml to use a block to reduce the transactions made.

.travis.yml, README.md, Vagrantfile, defaults/main.yml, tasks/configure.yml, tasks/extensions/contrib.yml, tasks/extensions/dev_headers.yml, tasks/extensions/postgis.yml, tasks/fedora.yml, tasks/install_yum.yml, tasks/main.yml, tests/docker/images/Dockerfile.fedora.27-builded
Added fedora image to vagrantfile
added extra vars for fedora in defaults/main.yml
added a fedora.yml
=> Fedora support

tasks/configure.yml
Fixes #284 .
This will verify that the actual version of the cluster that's in {{ postgresql_data_directory }}/PG_VERSION matches {{ postgresql_version }}.
=> Verify pg version

README.md
Change @gclough (Greg Clough) to a Maintainer
=> Change @gclough to a Maintainer

defaults/main.yml
Update to more recent default versions
=> Update to more recent default versions

tasks/configure.yml, tasks/extensions/dev_headers.yml, tasks/extensions/postgis.yml, tasks/install_apt.yml, tasks/install_yum.yml, templates/etc_systemd_system_postgresql.service.d_custom.conf.j2
Back again, let's see if the tests run now. If they go awry again I'll be unsure what's up... but we'll figure it out in time.
=> Deprecation warnings #322

defaults/main.yml, templates/postgresql.conf-10.j2, templates/postgresql.conf-9.6.j2
Fix force_parallel_mode to allow all three options on/off/regress
=> Fix force_parallel_mode to allow all three options on/off/regress

README.md, defaults/main.yml, tasks/extensions/contrib.yml, tasks/extensions/dev_headers.yml, tasks/extensions/postgis.yml, templates/postgresql.conf-10.j2, templates/postgresql.conf-11.j2, templates/postgresql.conf-11.orig, templates/postgresql.conf-9.1.j2, templates/postgresql.conf-9.2.j2, templates/postgresql.conf-9.3.j2, templates/postgresql.conf-9.4.j2, templates/postgresql.conf-9.5.j2, templates/postgresql.conf-9.6.j2, tests/docker/group_vars/all.yml, tests/vars.yml
Updated PR #333 and rebased it for merging
=> PostgresSQL v11 Support

tasks/install_dnf.yml
Could not get it working without this fix for fedora29
Signed-off-by: David Nyström <david.nystrom@ericsson.com>
=> Fix deps for fedora

README.md
Fix readme postgresql_database_schemas variable.  Fixes #399
=> Fix readme postgresql_database_schemas variable.  Fixes #399

templates/postgresql.conf-9.5.j2, templates/postgresql.conf-9.6.j2
=> Add missing log_replication_commands GUC

defaults/main.yml, templates/postgresql.conf-11.j2
Rebased postgresql.conf template with demo file to fix formatting, missing variables, etc.
=> Baseline v11 postgresql.conf against a fresh file

templates/postgresql.conf-10.j2, templates/postgresql.conf-9.3.j2, templates/postgresql.conf-9.4.j2, templates/postgresql.conf-9.5.j2, templates/postgresql.conf-9.6.j2
Fix incorrect or missing GUC variables
=> Fix incorrect or missing GUC variables

templates/postgresql.conf-10.j2, templates/postgresql.conf-9.5.j2, templates/postgresql.conf-9.6.j2
Add missing operator_precedence_warning GU
=> Add missing operator_precedence_warning GUC

tasks/check_pg_version_mismatch.yml
Change version tests to allow "Check Mode" ansible runs
=> Change version tests to allow "Check Mode" ansible runs

README.md, meta/main.yml
Update README for v12 & CentOS v8, plus new format for Galaxy metadata
=> Update README for v12 & CentOS v8, plus new format for Galaxy metadata

.travis.yml, README.md, Vagrantfile, vagrant-inventory
=> Disabled Fedora, as the build fails... even though nothing changed

meta/main.yml
Fix for travis ci role import.
=> Add role_name property. Should fix #467. [skip ci]

tests/vars.Debian.12.yml, vars/RedHat_8.yml
- add two packages for locale compatibility in rhel8
- add support for debian12 test
=> +2 packages in RHEL8 and debian12 support
